<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<p>readJson</p>
<form action="Json-upload" method="post" enctype="multipart/form-data">
    <div style="display: flex; flex-direction: row;">
        <input style="margin: auto; display: block; float: none;" class="btn btn-solid" type="file"
               name="drinks">
        <button style="margin: auto; display: block; float: none;" class="btn btn-solid" type="submit"
                class="">Upload
        </button>
    </div>
</form>
<a href="/start">Powrot</a>
</body>
</html>